# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Mon Sep 24 19:58:18 2012
#      by: pyside-uic 0.2.13 running on PySide 1.1.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui


class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(826, 863)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout_5 = QtGui.QGridLayout(self.centralWidget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_9 = QtGui.QLabel(self.centralWidget)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_8.addWidget(self.label_9)
        self.radioButton_mode0 = QtGui.QRadioButton(self.centralWidget)
        self.radioButton_mode0.setChecked(False)
        self.radioButton_mode0.setObjectName("radioButton_mode0")
        self.buttonGroup = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.radioButton_mode0, 0)
        self.horizontalLayout_8.addWidget(self.radioButton_mode0)
        self.radioButton_mode1 = QtGui.QRadioButton(self.centralWidget)
        self.radioButton_mode1.setChecked(True)
        self.radioButton_mode1.setObjectName("radioButton_mode1")
        self.buttonGroup.addButton(self.radioButton_mode1, 1)
        self.horizontalLayout_8.addWidget(self.radioButton_mode1)
        spacerItem = QtGui.QSpacerItem(
            40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem)
        self.pushButton_run = QtGui.QPushButton(self.centralWidget)
        self.pushButton_run.setObjectName("pushButton_run")
        self.horizontalLayout_8.addWidget(self.pushButton_run)
        self.gridLayout_5.addLayout(self.horizontalLayout_8, 0, 0, 1, 1)
        self.stackedWidget_mode = QtGui.QStackedWidget(self.centralWidget)
        self.stackedWidget_mode.setObjectName("stackedWidget_mode")
        self.page0 = QtGui.QWidget()
        self.page0.setObjectName("page0")
        self.gridLayout_6 = QtGui.QGridLayout(self.page0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_8 = QtGui.QLabel(self.page0)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_6.addWidget(self.label_8)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lineEdit_inputDatabase = QtGui.QLineEdit(self.page0)
        self.lineEdit_inputDatabase.setObjectName("lineEdit_inputDatabase")
        self.horizontalLayout_7.addWidget(self.lineEdit_inputDatabase)
        self.toolButton_open_inputDatabase = QtGui.QToolButton(self.page0)
        self.toolButton_open_inputDatabase.setObjectName("toolButton_open_inputDatabase")
        self.horizontalLayout_7.addWidget(self.toolButton_open_inputDatabase)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.gridLayout_6.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_7 = QtGui.QLabel(self.page0)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_5.addWidget(self.label_7)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lineEdit_output_stat = QtGui.QLineEdit(self.page0)
        self.lineEdit_output_stat.setObjectName("lineEdit_output_stat")
        self.horizontalLayout_6.addWidget(self.lineEdit_output_stat)
        self.toolButton_open_outdir = QtGui.QToolButton(self.page0)
        self.toolButton_open_outdir.setObjectName("toolButton_open_outdir")
        self.horizontalLayout_6.addWidget(self.toolButton_open_outdir)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.gridLayout_6.addLayout(self.verticalLayout_5, 1, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(
            20, 118, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem1, 2, 0, 1, 1)
        self.stackedWidget_mode.addWidget(self.page0)
        self.page1 = QtGui.QWidget()
        self.page1.setObjectName("page1")
        self.gridLayout_4 = QtGui.QGridLayout(self.page1)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame_Fasta = QtGui.QFrame(self.page1)
        self.frame_Fasta.setEnabled(True)
        self.frame_Fasta.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_Fasta.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_Fasta.setObjectName("frame_Fasta")
        self.gridLayout_3 = QtGui.QGridLayout(self.frame_Fasta)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtGui.QLabel(self.frame_Fasta)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        spacerItem2 = QtGui.QSpacerItem(
            40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.toolButton_open = QtGui.QToolButton(self.frame_Fasta)
        self.toolButton_open.setObjectName("toolButton_open")
        self.horizontalLayout_3.addWidget(self.toolButton_open)
        self.line_5 = QtGui.QFrame(self.frame_Fasta)
        self.line_5.setFrameShape(QtGui.QFrame.VLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout_3.addWidget(self.line_5)
        self.toolButton_clear = QtGui.QToolButton(self.frame_Fasta)
        self.toolButton_clear.setObjectName("toolButton_clear")
        self.horizontalLayout_3.addWidget(self.toolButton_clear)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.plainTextEdit_input = QtGui.QPlainTextEdit(self.frame_Fasta)
        self.plainTextEdit_input.setObjectName("plainTextEdit_input")
        self.gridLayout_3.addWidget(self.plainTextEdit_input, 1, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame_Fasta, 0, 0, 1, 1)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtGui.QLabel(self.page1)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lineEdit_output = QtGui.QLineEdit(self.page1)
        self.lineEdit_output.setObjectName("lineEdit_output")
        self.horizontalLayout_4.addWidget(self.lineEdit_output)
        self.toolButton_open_outfile = QtGui.QToolButton(self.page1)
        self.toolButton_open_outfile.setObjectName("toolButton_open_outfile")
        self.horizontalLayout_4.addWidget(self.toolButton_open_outfile)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.gridLayout_4.addLayout(self.verticalLayout_3, 1, 0, 1, 1)
        self.stackedWidget_mode.addWidget(self.page1)
        self.gridLayout_5.addWidget(self.stackedWidget_mode, 1, 0, 1, 1)
        self.line_3 = QtGui.QFrame(self.centralWidget)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_5.addWidget(self.line_3, 2, 0, 1, 1)
        self.frame = QtGui.QFrame(self.centralWidget)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtGui.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.codeListView_disable = QtGui.QListView(self.frame)
        self.codeListView_disable.setObjectName("codeListView_disable")
        self.verticalLayout_2.addWidget(self.codeListView_disable)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.line = QtGui.QFrame(self.frame)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_2.addWidget(self.line)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label = QtGui.QLabel(self.frame)
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayout_7.addWidget(self.label)
        spacerItem3 = QtGui.QSpacerItem(
            20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem3)
        self.pushButton_toEnable = QtGui.QPushButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_toEnable.sizePolicy().hasHeightForWidth())
        self.pushButton_toEnable.setSizePolicy(sizePolicy)
        self.pushButton_toEnable.setMinimumSize(QtCore.QSize(0, 48))
        self.pushButton_toEnable.setObjectName("pushButton_toEnable")
        self.verticalLayout_7.addWidget(self.pushButton_toEnable)
        self.pushButton_toDisable = QtGui.QPushButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_toDisable.sizePolicy().hasHeightForWidth())
        self.pushButton_toDisable.setSizePolicy(sizePolicy)
        self.pushButton_toDisable.setMinimumSize(QtCore.QSize(0, 48))
        self.pushButton_toDisable.setBaseSize(QtCore.QSize(0, 0))
        self.pushButton_toDisable.setObjectName("pushButton_toDisable")
        self.verticalLayout_7.addWidget(self.pushButton_toDisable)
        spacerItem4 = QtGui.QSpacerItem(
            20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem4)
        self.horizontalLayout_2.addLayout(self.verticalLayout_7)
        self.line_2 = QtGui.QFrame(self.frame)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_2.addWidget(self.line_2)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_3 = QtGui.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.codeListView_enable = QtGui.QListView(self.frame)
        self.codeListView_enable.setObjectName("codeListView_enable")
        self.verticalLayout_4.addWidget(self.codeListView_enable)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtGui.QLabel(self.frame)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.checkBox_GF4_all = QtGui.QCheckBox(self.frame)
        self.checkBox_GF4_all.setChecked(False)
        self.checkBox_GF4_all.setObjectName("checkBox_GF4_all")
        self.horizontalLayout_5.addWidget(self.checkBox_GF4_all)
        self.lineEdit_GF4 = QtGui.QLineEdit(self.frame)
        self.lineEdit_GF4.setEnabled(True)
        self.lineEdit_GF4.setObjectName("lineEdit_GF4")
        self.horizontalLayout_5.addWidget(self.lineEdit_GF4)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 1, 0, 1, 1)
        self.gridLayout_5.addWidget(self.frame, 3, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 826, 25))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.logDock = QtGui.QDockWidget(MainWindow)
        self.logDock.setEnabled(True)
        self.logDock.setObjectName("logDock")
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout = QtGui.QGridLayout(self.dockWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.logTextBrowser = QtGui.QTextBrowser(self.dockWidgetContents)
        self.logTextBrowser.setObjectName("logTextBrowser")
        self.verticalLayout.addWidget(self.logTextBrowser)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.logDock.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.logDock)

        self.retranslateUi(MainWindow)
        self.stackedWidget_mode.setCurrentIndex(1)
        QtCore.QObject.connect(self.checkBox_GF4_all, QtCore.SIGNAL(
            "toggled(bool)"), self.lineEdit_GF4.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate(
            "MainWindow", "Gene code analyzer", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate(
            "MainWindow", "Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_mode0.setText(QtGui.QApplication.translate(
            "MainWindow", "Survival Analysis (Code Analysis + Statistical tests)", None,
            QtGui.QApplication.UnicodeUTF8))
        self.radioButton_mode1.setText(QtGui.QApplication.translate(
            "MainWindow", "Code Analysis", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_run.setText(
            QtGui.QApplication.translate("MainWindow", "Run", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate(
            "MainWindow", "Input Database (CSV format)", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_open_inputDatabase.setText(
            QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate(
            "MainWindow", "Output directory (new directory will be created in this directory)",
            None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_open_outdir.setText(
            QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate(
            "MainWindow", "Input sequences (FASTA format)", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_open.setText(QtGui.QApplication.translate(
            "MainWindow", "Append from File", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_clear.setText(
            QtGui.QApplication.translate("MainWindow", "Clear", None,
                                         QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate(
            "MainWindow", "Output file (CSV format)", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_open_outfile.setText(
            QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate(
            "MainWindow", "Available code", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_toEnable.setText(
            QtGui.QApplication.translate("MainWindow", "->", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_toDisable.setText(
            QtGui.QApplication.translate("MainWindow", "<-", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate(
            "MainWindow", "Code to use", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate(
            "MainWindow", "coordinate of GF(4) elements (0, 1, 2, 3):", None,
            QtGui.QApplication.UnicodeUTF8))
        self.checkBox_GF4_all.setText(QtGui.QApplication.translate(
            "MainWindow", "All patterns", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_GF4.setText(
            QtGui.QApplication.translate("MainWindow", "ATGC", None,
                                         QtGui.QApplication.UnicodeUTF8))
