# Reference: https://gist.github.com/dan-blanchard/7045057
language: python
python:
    - 2.7
    - 3.4
# Setup anaconda
before_install:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/miniconda/bin:$PATH
    - conda update --yes conda
    # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
    - sudo rm -rf /dev/shm
    - sudo ln -s /run/shm /dev/shm
# Install packages
install:
    - sudo apt-get install libqt4-dev
    - conda install --yes python=$TRAVIS_PYTHON_VERSION pip setuptools numpy scipy matplotlib nose dateutil
    # Omit pip install PySide
    - pip install --find-links https://parkin.github.io/python-wheelhouse/ --use-wheel PySide;
    - python ~/virtualenv/python${TRAVIS_PYTHON_VERSION}/bin/pyside_postinstall.py -install

    - sed '/./s/PySide//g' requirements.txt > requirements.txt
    - python setup.py develop
script: nosetests
