language: python
python:
    - "2.7_with_system_site_packages"
    - "3.2_with_system_site_packages"
before_install:
    - sudo apt-get update
    - sudo apt-get install python-numpy python-scipy
    - sudo apt-get install libqt4-dev
install:
    - pip install -q --use-mirrors python-dateutil
    - pip install PySide --no-index --find-links https://parkin.github.io/python-wheelhouse/
    - python ~/virtualenv/python${TRAVIS_PYTHON_VERSION}/bin/pyside_postinstall.py -install
    - python setup.py install
script: nosetests
