# References: [1] https://github.com/Jorge-C/ordination/blob/master/.travis.yml
#             [2] https://gist.github.com/dan-blanchard/7045057
language: python
python:
    - 2.7
    - 3.3
# Setup anaconda
before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/miniconda/bin:$PATH
    - conda update --yes conda
    # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
    - sudo rm -rf /dev/shm
    - sudo ln -s /run/shm /dev/shm
# Install packages
install:
    - sudo apt-get install libqt4-dev
    - conda install --yes python=$TRAVIS_PYTHON_VERSION setuptools numpy scipy matplotlib nose dateutil
#    - pip install pytest  # not yet available for py3 in anaconda
    - pip install --find-links https://parkin.github.io/python-wheelhouse/ --use-wheel PySide;
    # Travis CI servers use virtualenvs, so we need to finish the install by the following
    - python ~/virtualenv/python${TRAVIS_PYTHON_VERSION}/bin/pyside_postinstall.py -install
    - python setup.py install
script: nosetests
